name: inn-service
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  inn-job:
    runs-on: ubuntu-latest
    services:
      inn-service:
        image: cclauss/inn
        ports:
          - 119:119
          - 563:563
    steps:
      - run: pip install --user pynntp
      - shell: python
        run: |
            import nntp
            nntp_client = nntp.NNTPClient("localhost")
            print(f"{tuple(nntp_client.list_newsgroups()) = }")
            nntp_client.quit()
