name: inn-service
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  inn-job:
    strategy:
      fail-fast: false
      matrix:
        service: [cclauss/inn, greenbender/inn]
    runs-on: ubuntu-latest
    services:
      inn-service:
        image: matrix.${{ matrix.service }}
        ports:
          - 119:119
          - 563:563
    steps:
      - uses: actions/checkout@v4
        with:
          repository: greenbender/pynntp
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install --upgrade pip
      - run: pip install pytest
      - run: pip install --editable .
      - run: pytest  # Run the pynntp tests
      - shell: python
        run: |
            import nntp
            nntp_client = nntp.NNTPClient("localhost")
            print(f"{tuple(nntp_client.list_newsgroups()) = }")
            nntp_client.quit()
